"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import html2canvas from "html-to-image";
import { saveAs } from "file-saver";

const roastLines = [
  "Your node uptime is lower than your self-esteem.",
    "You say you’re decentralized, but you’re always in her DMs.",
      "You forked twice and still didn’t improve performance.",
        "You propagate slower than grandma’s Wi-Fi.",
          "Optimum called—said your latency is embarrassing.",
            "Your packets get dropped more than your mixtapes.",
              "Even Optimum’s mumP2P can’t propagate your personality.",
                "You debug like you’re in denial.",
                  "Even Solidity throws fewer errors than you do.",
                    "You coded your life in spaghetti logic.",
                      "You commit to GitHub more than you commit to relationships.",
                        "You bought the top and sold the rumor.",
                          "Your liquidity pool is 99% tears.",
                            "You diversify your regrets, not your portfolio.",
                              "Even MEV bots avoid your trades.",
                                "You talk decentralization, but centralize your excuses.",
                                  "Your reliability score is -404.",
                                    "Even Optimum can’t optimize that attitude.",
                                      "Your node’s asleep — like your ambition.",
                                        "You need a reorg in your life.",
                                          "You’re like testnet rewards — promised, never delivered.",
                                            "You optimize nothing but chaos.",
                                              "You got rug-pulled by common sense.",
                                                "Your aura screams 'pending transaction.'",
                                                  "Your energy glows blue but your effort barely loads.",
                                                    "Validator core: 2%. Ego core: 98%.",
                                                      "You’ve been optimized for disappointment.",
                                                        "Memory waves unstable. Confidence missing.",
                                                          "Aura level: testnet-tier.",
                                                            "You’re proof block propagation isn’t instant.",
                                                              "Even your crush slashed your stake.",
                                                                "You’re a validator with no delegation.",
                                                                  "You gossip more than Ethereum but say less.",
                                                                    "Your throughput is fine… if we’re measuring disappointment.",
                                                                      "You lag harder than a Discord stream on hotel Wi-Fi.",
                                                                        "You compress data but inflate your ego.",
                                                                          "Your brain needs a firmware update.",
                                                                            "You’re still console.logging your feelings.",
                                                                              "You’re like an RPC outage with feelings.",
                                                                                "You’re not even in the mempool.",
                                                                                  "You scale horizontally and still fall short vertically.",
                                                                                    "You optimize for drama, not performance.",
                                                                                      "You need a reboot, not therapy.",
                                                                                        "You’re gasless — both ways.",
                                                                                          "Even your shadow unsubscribed.",
                                                                                            "You’re proof 'beta' can be permanent.",
                                                                                              "Aura detected: broke but hopeful.",
                                                                                                "Your signals bounce like your attention span.",
                                                                                                  "You reached consensus... with failure.",
                                                                                                    "Validator core overheated. Try again later.",
                                                                                                      "You fork drama, not repos.",
                                                                                                        "Your aura’s blue, your vibe’s off-chain.",
                                                                                                          "You’d fail a ping test to reality.",
                                                                                                            "You’re a single point of failure in human form.",
                                                                                                              "Even your packets left for faster routes.",
                                                                                                                "Optimum would throttle your attitude.",
                                                                                                                  "You buffer through every conversation.",
                                                                                                                    "You’re proof redundancy has limits.",
                                                                                                                      "You need less latency and more therapy.",
                                                                                                                        "Your blocks never finalize.",
                                                                                                                          "You’d get slashed in a trust fall.",
                                                                                                                            "Consensus failed: too emotional.",
                                                                                                                              "You’re an unverified node in every sense.",
                                                                                                                                "Your PFP has more confidence than you.",
                                                                                                                                  "You dropped your stake and your standards.",
                                                                                                                                    "Aura syncing... forever.",
                                                                                                                                      "Your meme hash rate is below testnet.",
                                                                                                                                        "Reorg detected — your personality.",
                                                                                                                                          "Your uptime report says 'lol.'",
                                                                                                                                            "Bandwidth: none. Opinions: plenty.",
                                                                                                                                              "Packet loss = life story.",
                                                                                                                                                "You gossip without propagation.",
                                                                                                                                                  "Your aura’s blue but your wallet’s red.",
                                                                                                                                                    "You forked your feelings.",
                                                                                                                                                      "RPC call failed — emotional overload.",
                                                                                                                                                        "Even your validator ghosted you.",
                                                                                                                                                          "You scale like Solana on a bad day.",
                                                                                                                                                            "Optimum can’t optimize this mess.",
                                                                                                                                                              "You’re not decentralized, you’re just lost.",
                                                                                                                                                                "Your logs say 'bro what are you doing.'",
                                                                                                                                                                  "You lag IRL.",
                                                                                                                                                                    "Node reputation: clown-tier.",
                                                                                                                                                                      "Your aura’s cached, not real.",
                                                                                                                                                                        "You’d timeout in a conversation.",
                                                                                                                                                                          "Gas price of your ego: unaffordable.",
                                                                                                                                                                            "Even latency avoids you.",
                                                                                                                                                                              "You propagate excuses faster than blocks.",
                                                                                                                                                                                "Your validator report says 'bro stop.'",
                                                                                                                                                                                  "You talk bandwidth, but you’re static.",
                                                                                                                                                                                    "Even your aura rate-limited you.",
                                                                                                                                                                                      "You broadcast, no one listens.",
                                                                                                                                                                                        "You’re an edge node for bad takes.",
                                                                                                                                                                                          "RPC disconnected — user error.",
                                                                                                                                                                                            "You talk consensus, but you’re divided internally.",
                                                                                                                                                                                              "Block height: emotionally low.",
                                                                                                                                                                                                "Aura corrupted: missing self-worth.",
                                                                                                                                                                                                  "Optimum roasted you, automatically.",
                                                                                                                                                                                                    "Protocol suggestion: touch grass."
                                                                                                                                                                                                    ];

                                                                                                                                                                                                    export default function RoastButton() {
                                                                                                                                                                                                      const [image, setImage] = useState(null);
                                                                                                                                                                                                        const [roast, setRoast] = useState("");

                                                                                                                                                                                                          const handleRoast = () => {
                                                                                                                                                                                                              if (!image) return alert("Upload your image first!");
                                                                                                                                                                                                                  const randomRoast = roastLines[Math.floor(Math.random() * roastLines.length)];
                                                                                                                                                                                                                      setRoast(randomRoast);
                                                                                                                                                                                                                        };

                                                                                                                                                                                                                          const handleDownload = async () => {
                                                                                                                                                                                                                              const node = document.getElementById("roast-result");
                                                                                                                                                                                                                                  const blob = await html2canvas.toBlob(node);
                                                                                                                                                                                                                                      saveAs(blob, "optimum_roast.png");
                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                              <div className="flex flex-col items-center gap-4 mt-6">
                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                            type="file"
                                                                                                                                                                                                                                                                    accept="image/*"
                                                                                                                                                                                                                                                                            onChange={(e) => setImage(URL.createObjectURL(e.target.files[0]))}
                                                                                                                                                                                                                                                                                    className="p-2 border border-gray-300 rounded-lg"
                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                <motion.button
                                                                                                                                                                                                                                                                                                        whileTap={{ scale: 0.95 }}
                                                                                                                                                                                                                                                                                                                onClick={handleRoast}
                                                                                                                                                                                                                                                                                                                        className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-semibold shadow-md"
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                      Roast Me 🔥
                                                                                                                                                                                                                                                                                                                                            </motion.button>

                                                                                                                                                                                                                                                                                                                                                  {roast && (
                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                    id="roast-result"
                                                                                                                                                                                                                                                                                                                                                                              className="mt-6 p-4 bg-gray-900 text-white rounded-xl shadow-lg text-center"
                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                                                                                            src={image}
                                                                                                                                                                                                                                                                                                                                                                                                                        alt="Uploaded"
                                                                                                                                                                                                                                                                                                                                                                                                                                    className="max-w-xs mx-auto rounded-xl mb-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-lg font-medium">{roast}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-gray-400 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              made with love by nicole2288 💙 and beginner
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handleDownload}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mt-3 bg-gray-700 hover:bg-gray-800 text-sm px-4 py-2 rounded-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Share on X
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }