"use client";

import { motion } from "framer-motion";
import Image from "next/image";
import { useSession, signIn, signOut } from "next-auth/react";

export default function HomePage() {
  const { data: session, status } = useSession();

    return (
        <main className="flex flex-col items-center justify-center min-h-screen w-full bg-black text-center relative overflow-hidden px-4 sm:px-8">
              {/* Background Glow */}
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_rgba(255,255,0,0.15)_0%,_transparent_70%)] blur-3xl"></div>

                          {/* Title */}
                                <motion.h1
                                        className="font-black text-[clamp(2rem,5vw,4.5rem)] bg-gradient-to-r from-red-500 via-blue-400 to-yellow-400 text-transparent bg-clip-text drop-shadow-lg leading-tight animate-[gradientShift_5s_linear_infinite]"
                                                initial={{ opacity: 0, scale: 0.8 }}
                                                        animate={{ opacity: 1, scale: 1 }}
                                                                transition={{ duration: 1 }}
                                                                      >
                                                                              Optimum Roast Generator
                                                                                    </motion.h1>

                                                                                          {/* Subtitle */}
                                                                                                <motion.p
                                                                                                        className="mt-4 font-extrabold text-[clamp(0.95rem,2.5vw,1.2rem)] max-w-[90vw] sm:max-w-xl md:max-w-2xl leading-relaxed bg-gradient-to-r from-red-400 via-blue-400 to-yellow-400 text-transparent bg-clip-text animate-[gradientShift_6s_linear_infinite]"
                                                                                                                initial={{ opacity: 0 }}
                                                                                                                        animate={{ opacity: 1 }}
                                                                                                                                transition={{ delay: 0.4, duration: 1 }}
                                                                                                                                      >
                                                                                                                                              Connect your <span className="font-black">Discord aura</span>.<br />
                                                                                                                                                      Get roasted by the <span className="font-black">network</span>.<br />
                                                                                                                                                              No mercy. Pure Optimum energy ⚡
                                                                                                                                                                    </motion.p>

                                                                                                                                                                          {/* Auth Section */}
                                                                                                                                                                                {status === "loading" ? (
                                                                                                                                                                                        <p className="mt-8 font-black text-yellow-400 animate-pulse text-[clamp(0.85rem,2vw,1rem)]">
                                                                                                                                                                                                  Connecting to Discord...
                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                ) : !session ? (
                                                                                                                                                                                                                        <motion.button
                                                                                                                                                                                                                                  onClick={() => signIn("discord")}
                                                                                                                                                                                                                                            initial={{ opacity: 0, scale: 0.8 }}
                                                                                                                                                                                                                                                      animate={{ opacity: 1, scale: 1 }}
                                                                                                                                                                                                                                                                transition={{ delay: 0.8, duration: 0.8 }}
                                                                                                                                                                                                                                                                          className="mt-10 px-6 sm:px-8 py-3 sm:py-4 font-black rounded-2xl shadow-lg transition-all duration-300 text-[clamp(0.85rem,2vw,1rem)] relative overflow-hidden bg-gradient-to-r from-red-500 via-blue-400 to-yellow-400 text-transparent bg-clip-text animate-[gradientShift_8s_linear_infinite]"
                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                            Sign in with Discord
                                                                                                                                                                                                                                                                                                    </motion.button>
                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                  <motion.div
                                                                                                                                                                                                                                                                                                                            className="mt-10 flex flex-col items-center space-y-5"
                                                                                                                                                                                                                                                                                                                                      initial={{ opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                animate={{ opacity: 1 }}
                                                                                                                                                                                                                                                                                                                                                          transition={{ delay: 0.3, duration: 1 }}
                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                            <Image
                                                                                                                                                                                                                                                                                                                                                                                        src={session.user.image}
                                                                                                                                                                                                                                                                                                                                                                                                    alt="Discord Avatar"
                                                                                                                                                                                                                                                                                                                                                                                                                width={100}
                                                                                                                                                                                                                                                                                                                                                                                                                            height={100}
                                                                                                                                                                                                                                                                                                                                                                                                                                        className="rounded-full border-2 border-blue-400 shadow-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-[clamp(1.2rem,3vw,2rem)] font-black bg-gradient-to-r from-red-500 via-blue-400 to-yellow-400 text-transparent bg-clip-text animate-[gradientShift_7s_linear_infinite]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {session.user.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="italic font-black leading-relaxed max-w-[90vw] sm:max-w-xl md:max-w-2xl text-[clamp(0.9rem,2.5vw,1.2rem)] bg-gradient-to-r from-red-400 via-blue-400 to-yellow-400 text-transparent bg-clip-text animate-[gradientShift_6s_linear_infinite]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        You’ve achieved <span className="font-black">enlightenment</span> but still can’t find your private key 🔥
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => signOut()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="px-5 sm:px-6 py-2 sm:py-3 font-black rounded-xl shadow-md transition-all duration-300 text-[clamp(0.85rem,2vw,1rem)] relative overflow-hidden bg-gradient-to-r from-red-500 via-blue-400 to-yellow-400 text-transparent bg-clip-text animate-[gradientShift_8s_linear_infinite]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Sign Out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <footer className="absolute bottom-5 font-black text-[clamp(0.7rem,1.8vw,0.9rem)] text-gray-300 animate-[floatFooter_6s_ease-in-out_infinite]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Made with ❤️ by <span className="text-red-500">nicole2288</span> &{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-yellow-400">beginner</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }